# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e7a74c2291da119ec0affe2c5e7c8fcf7fa6a95a309a0cedf57c51e677c37db5b2f3cbb57148c391bee1023b42a6e91dec3ab3d93c0c7f412895029aa00f42d

test:
  secret_key_base: 204378aa170802f87557f4a1acd4db21e5952468afca77b85767b9bd541b284a607fdd8f7c30b7af86375064be10c117156a26d362aac24f3447c9bd3ed6b95f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
